### ISSUE TITLE
Could you share your environment?And  can you release your pretrained models?

### ISSUE THREAD

**Issue by shallweiwei** [CandleLabAI/TPFNet#1]
I am a newcomer in this field,so is this all of your code?could you share some examples to run your code?

**Comment by shallweiwei** [comment]
I roughly glanced at your code,it seems there is only code of Part1,and I think your code is very concise and clear！^_^

**Comment by Onkarsus13** [comment]
i think both of stages code is there

**Comment by shallweiwei** [comment]
This is a question from a year ago, and as far as I remember, the model was incomplete and missing weights. @Onkarsus13

**Comment by Onkarsus13** [comment]
Actually, It was previously there but one thing is there after we privatized the weights
but if you want i can share one updated code based on Diffusion its working much better than this 
It would be like TPFNet++ 

```
https://github.com/Onkarsus13/Diff_SceneTextEraser
```

**Comment by shallweiwei** [comment]
Thank you for sharing.
